/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2016-07-16 21:02:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bdeb.dao.ProduitDAOImpl;
import bdeb.model.Produit;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Detail de produits</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/detail.css\" >\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#main {\n");
      out.write("\twidth: 1060px;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin-left: auto;\n");
      out.write("\tmargin-right: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#head {\n");
      out.write("\theight: 200px;\n");
      out.write("\tbackground-color: #F5F5F5;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tmargin-top: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#head-link {\n");
      out.write("\theight: 50px;\n");
      out.write("\tline-height: 30px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tbackground-color: #F5F5F5;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#content {\n");
      out.write("\twidth: 1060px;\n");
      out.write("\tmin-height: 430px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tfloat: left;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#footer {\n");
      out.write("\theight: 50px;\n");
      out.write("\tclear: both;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tbackground-color: #F8F8FF;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t");

		
		String codeProduit = "";
		if (request.getParameter("codeProduit") != null) {
			codeProduit = request.getParameter("codeProduit");
		}

		ProduitDAOImpl produitDAO = new ProduitDAOImpl();
	
      out.write("\n");
      out.write("\t<div id=\"main\">\n");
      out.write("\t\t<div id=\"head\">\n");
      out.write("\t\t\t<img src=\"images/baner.jpg\" width=\"1057\" height=\"200\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"head-link\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\n");
      out.write("\t\t<div id=\"content\">\n");
      out.write("\t\t\t<div class=\"left-1\">\n");
      out.write("                            <img src=\"produits/");
      out.print(produitDAO.getProduitParCode(Integer.parseInt(codeProduit)).getImageProduit());
      out.write("\"\n");
      out.write("\t\t\t\t\twidth=\"200\" height=\"200\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"left-2\">\n");
      out.write("\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t<tr class=\"row1\">\n");
      out.write("                                            <td class=\"col2\" colspan=\"2\"\n");
      out.write("\t\t\t\t\t\tstyle=\"padding: 10px; color: blue; font-size: 15px; text-transform: uppercase; text-align: center; font-weight: bold\">\n");
      out.write("                                                    Code Produit:");
      out.print(produitDAO.getProduitParCode(Integer.parseInt(codeProduit)).getCodeProduit());
      out.write("\n");
      out.write("                                            </td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("                                        <tr class=\"row1\">\n");
      out.write("                                            <td class=\"col2\" colspan=\"2\"\n");
      out.write("\t\t\t\t\t\tstyle=\"padding: 10px; color: blue; font-size: 15px; text-transform: uppercase; text-align: center; font-weight: bold\">\n");
      out.write("                                                Nom Produit:");
      out.print(produitDAO.getProduitParCode(Integer.parseInt(codeProduit)).getNomProduit());
      out.write("\n");
      out.write("                                            </td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("                                        <tr class=\"row1\">\n");
      out.write("                                            <td class=\"col2\" colspan=\"2\"\n");
      out.write("\t\t\t\t\t\tstyle=\"padding: 10px; color: blue; font-size: 15px; text-transform: uppercase; text-align: center; font-weight: bold\">\n");
      out.write("                                                Prix:");
      out.print(produitDAO.getProduitParCode(Integer.parseInt(codeProduit)).getPrixProduit());
      out.write(" CAD\n");
      out.write("                                            </td>\n");
      out.write("\t\t\t\t\t</tr>\t\t\n");
      out.write("                                        <tr class=\"row1\">\n");
      out.write("                                            <td class=\"col2\" colspan=\"2\"\n");
      out.write("\t\t\t\t\t\tstyle=\"padding: 10px; color: blue; font-size: 15px; text-transform: uppercase; text-align: center; font-weight: bold\">\n");
      out.write("                                                Marque:");
      out.print(produitDAO.getProduitParCode(Integer.parseInt(codeProduit)).getMarqueProduit());
      out.write("\n");
      out.write("                                            </td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div\n");
      out.write("\t\t\t\tstyle=\"margin-left: auto; margin-right: auto; text-align: center; margin-top: 10px; padding: 10px; clear: both;\">\n");
      out.write("\t\t\t\t<a href=\"PanierServlet?command=insererPanier&codeProduit=");
      out.print(codeProduit);
      out.write("\">\n");
      out.write("                                    <img src=\"images/icon-cart.png\" />\n");
      out.write("                                </a>\n");
      out.write("\t\t\t</div>\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"footer\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
