/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2016-07-16 21:02:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bdeb.model.Panier;
import java.util.ArrayList;
import bdeb.dao.ProduitDAOImpl;

public final class panier_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <title>Panier</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/panier.css\" />\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#main {\n");
      out.write("\twidth: 1060px;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin-left: auto;\n");
      out.write("\tmargin-right: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#head {\n");
      out.write("\theight: 200px;\n");
      out.write("\tbackground-color: #F5F5F5;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tmargin-top: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#head-link {\n");
      out.write("\theight: 50px;\n");
      out.write("\tline-height: 30px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tbackground-color: #F5F5F5;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#content {\n");
      out.write("\twidth: 1060px;\n");
      out.write("\tmin-height: 430px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tfloat: left;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#footer {\n");
      out.write("\theight: 50px;\n");
      out.write("\tclear: both;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tbackground-color: #F8F8FF;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"main\">\n");
      out.write("\t\t<div id=\"head\">\t<img src=\"images/baner.jpg\" width=\"1057\" height=\"200\"/>\t</div>\n");
      out.write("\t\t<div id=\"head-link\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\n");
      out.write("\t\t<div id=\"content\">\n");
      out.write("\t\t\t<h1 style=\"margin-left: 50px;\">Votre panier</h1>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"shopping-cart\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"column-labels\">\t\t\t\t\t\n");
      out.write("                                        <label class=\"product-details\">Produit</label> \n");
      out.write("                                        <label class=\"product-price\">Prix</label>\n");
      out.write("                                        <label class=\"product-quantity\">Quantité</label>\n");
      out.write("                                        <label class=\"product-line-price\">Total a payer</label>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t");

					ProduitDAOImpl produitDAO = new ProduitDAOImpl();					
					double total = 0;
					ArrayList<Panier> panier = (ArrayList<Panier>)session.getAttribute("panier");
				
      out.write("\n");
      out.write("\t\t\t\t");

					if (panier != null) {
						for (Panier p : panier) {
							total = total + (p.getQuantite() * produitDAO.getProduitParCode(
											p.getProduit().getCodeProduit()).getPrixProduit());
				
      out.write("\n");
      out.write("\t\t\t\t<div class=\"product\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"product-details\">\n");
      out.write("\t\t\t\t\t\t<div class=\"product-title\">\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(produitDAO.getProduitParCode(p.getProduit().getCodeProduit()).getNomProduit());
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<p class=\"product-description\"></p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"product-price\">");
      out.print(produitDAO.getProduitParCode(p.getProduit().getCodeProduit()).getPrixProduit());
      out.write("\n");
      out.write("                                            CAD\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"product-quantity\">\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" value=\"");
      out.print(p.getQuantite());
      out.write("\"disabled=\"disabled\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"product-line-price\">");
      out.print((produitDAO.getProduitParCode(
							p.getProduit().getCodeProduit()).getPrixProduit()
							* p.getQuantite()));
      out.write("\n");
      out.write("\t\t\t\t\t\tCAD\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\n");
      out.write("\t\t\t\t<div class=\"totals\">\n");
      out.write("\t\t\t\t\t<div class=\"totals-item\">\n");
      out.write("\t\t\t\t\t\t<label>Total a payer</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"totals-value\" id=\"cart-subtotal\">");
      out.print(total);
      out.write(" CAD</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<a class=\"checkout\" href=\"#\" style=\"text-decoration: none;\">Payer</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"footer\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
