/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2016-07-16 21:06:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chercher_005ftrajet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeSpring.jsp", out, false);
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeBootstrap.jsp", out, false);
      out.write("    \r\n");
      out.write("       \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"newcss.css\">\r\n");
      out.write("        <title>Recherche trajet - Quebecovoiturage</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeHeader.jsp", out, false);
      out.write("    \r\n");
      out.write("      <div id=\"main\" class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("          <form class=\"form\" role=\"form\" action=\"chercher_trajet.htm\" method=\"POST\">\r\n");
      out.write("      <fieldset>\r\n");
      out.write("      <legend>Recherche de trajet</legend>\r\n");
      out.write("      \r\n");
      out.write("       <!-- Trigger the modal with a button -->\r\n");
      out.write("  <button type=\"button\" class=\"btn btn-info btn-xs\" data-toggle=\"modal\" data-target=\"#myModal\">Astuce</button>\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">Astuce de recherche</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <p>S.V.P Veuillez saisir au moins un critère de recherche pour chercher des trajets spécifiques.\r\n");
      out.write("          A défaut, cliquer sur le bouton  «chercher» pour afficher tous les trajets</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Fermer</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div class=\"form-group \">\r\n");
      out.write("      <label for=\"villedepart\">Ville de départ:</label>\r\n");
      out.write("      <input type=\"text\" name=\"villedepart\" class=\"form-control\" id=\"villedepart\" size=\"30\" maxlength=\"30\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"villearrivee\">Ville d'arrivée:</label>\r\n");
      out.write("      <input type=\"text\" name=\"villearrivee\" class=\"form-control\" id=\"villearrivee\" size=\"30\" maxlength=\"30\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"datearrivee\">Date et heure de départ:</label>\r\n");
      out.write("      <div class=\"input-group date\" >\r\n");
      out.write("          <input type=\"datetime-local\" name=\"datedepart\" class=\"form-control\" data-provide=\"datepicker\" id=\"datetimepicker1\">\r\n");
      out.write("      <span class=\"input-group-addon\">\r\n");
      out.write("           <span class=\"glyphicon glyphicon-calendar\"></span>\r\n");
      out.write("       </span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("          \r\n");
      out.write("          <button class=\"btn btn-primary btn-md glyphicon glyphicon-search\" value=\"chercher\" \r\n");
      out.write("                  type=\"submit\"> Chercher </button>\r\n");
      out.write("      \r\n");
      out.write("      </fieldset>\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" </div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeFooter.jsp", out, false);
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("           </div>          \r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $('[data-toggle=\"tooltip\"]').tooltip();   \r\n");
      out.write("        });\r\n");
      out.write("        $(function() {\r\n");
      out.write("\r\n");
      out.write("            $( '#datetimepicker1' ).datetimepicker();\r\n");
      out.write("\r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("        function showTable(){\r\n");
      out.write("         document.getElementById('table').style.visibility = \"visible\";\r\n");
      out.write("         }\r\n");
      out.write("         function hideTable(){\r\n");
      out.write("         document.getElementById('table').style.visibility = \"hidden\";\r\n");
      out.write("         }\r\n");
      out.write("  \r\n");
      out.write("      </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
