/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2016-07-16 21:06:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class includeMessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("        \n");
      out.write("<section>\n");
      out.write("     \n");
      out.write("       \n");
      out.write("         <img   class=\"img-rounded img-responsive\" id=\"ph1\" src=\"images/jennifer.jpg\"  width=\"50\" height=\"50\" alt=\"photo1\"/>\n");
      out.write("<span id=\"s1\">Message laissé à Jennifer</span>\n");
      out.write("  <a id=\"tool\" href=\"#\" data-toggle=\"tooltip\" title=\" Avis laissé à Florent S \n");
      out.write("« Trajet très agréable, rapide et très sympa. Vous pouvez lui faire confiance, n'hésitez pas à covoiturer avec Florent. » \n");
      out.write("Corinne C\"> <span>Cliquer Ici</span></a>\n");
      out.write("\n");
      out.write("<img   class=\"img-rounded img-responsive\" id=\"ph2\" src=\"images/rihanna.jpg\"  width=\"50\" height=\"50\" alt=\"photo1\"/>\n");
      out.write("    \n");
      out.write("<span id=\"s2\">Message laissé à Rihanna</span>\n");
      out.write("    \n");
      out.write("  <a id=\"tool1\" href=\"#\" data-toggle=\"tooltip\" title=\" Avis laissé à Florent S \n");
      out.write("« Trajet très agréable, rapide et très sympa. Vous pouvez lui faire confiance, n'hésitez pas à covoiturer avec Florent. » \n");
      out.write("Corinne C\"> <span>Cliquer Ici</span></a>\n");
      out.write("<img   class=\"img-rounded img-responsive\" id=\"ph3\" src=\"images/brattpit.jpg\" width=\"50\" height=\"50\"  alt=\"photo1\"/>\n");
      out.write("\n");
      out.write("<span id=\"s3\">Message laissé à Bratt Pit</span>\n");
      out.write("    \n");
      out.write("  <a  id=\"tool3\" href=\"#\" data-toggle=\"tooltip\" title=\" Avis laissé à Florent S \n");
      out.write("« Trajet très agréable, rapide et très sympa. Vous pouvez lui faire confiance, n'hésitez pas à covoiturer avec Florent. » \n");
      out.write("Corinne C\"> <span>Cliquer Ici</span></a>\n");
      out.write("\n");
      out.write(" </article>\n");
      out.write("</section>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
