/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2016-07-16 21:07:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inscription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"erreur.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeSpring.jsp", out, false);
      out.write(" \n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeBootstrap.jsp", out, false);
      out.write("   \n");
      out.write("                    \n");
      out.write("         <link rel=\"stylesheet\" type=\"text/css\" href=\"newcss.css\">\n");
      out.write("        <title>Inscription - Quebecovoiturage</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeHeader.jsp", out, false);
      out.write("         \t\t \t\n");
      out.write("        <div id=\"main\" class=\"container-fluid\">\n");
      out.write("          <form\n");
      out.write("                  action=\"inscription.htm\"  method=\"POST\">\n");
      out.write("              <fieldset>\n");
      out.write("                 <legend>Inscription</legend>\n");
      out.write("                 \n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                 <label for=\"nom\">Nom:</label>\n");
      out.write("                 <input class=\"form-control\" type=\"text\" name=\"nom\" value=\"\"  id=\"nom\" required=\"\" maxlength=\"30\"/>\n");
      out.write("                 </div>\n");
      out.write("                 \n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                    <label for=\"prenom\">Prenom:</label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"prenom\" value=\"\"  id=\"prenom\" required=\"\" maxlength=\"30\"/>\n");
      out.write("                 </div>\n");
      out.write("                 \n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                    <label for=\"datenaissance\">Date de naissance:</label>\n");
      out.write("                    <input class=\"form-control\" type=\"date\" name=\"datenaissance\" id=\"datenaissance\" required=\"\"/>\n");
      out.write("                 </div>\n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                     <label for=\"adresseno\">Numéro adresse et Appartement</label>\n");
      out.write("                     <input type=\"text\" class=\"form-control\" name=\"adresseno\" id=\"adresseno\" value=\"\" required=\"\" maxlength=\"30\" placeholder=\"adresse n° - appartement n°\" />\n");
      out.write("                 </div>\n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                     <label for=\"nomrue\">Nom de rue / boulevard:</label>\n");
      out.write("                     <input type=\"text\" class=\"form-control\" name=\"nomrue\" id=\"nomrue\" value=\"\" required=\"\" maxlength=\"30\" />\n");
      out.write("                 </div>\n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                    <label for=\"ville\">Ville:</label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"ville\" value=\"\"  id=\"ville\" required=\"\" maxlength=\"30\"/>\n");
      out.write("                 </div>\n");
      out.write("                 \n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                    <label for=\"codepostal\">Code postal:</label>\n");
      out.write("                    <input class=\"form-control\" type=\"text\" name=\"codepostal\" value=\"\"  id=\"codepostal\" required=\"\" maxlength=\"6\"/>\n");
      out.write("                 </div>\n");
      out.write("                 \n");
      out.write("                 <div class=\"form-group\">\n");
      out.write("                    <label for=\"tel\">Téléphone:</label>\n");
      out.write("                    <input class=\"form-control\" type=\"tel\" name=\"tel\" value=\"\"  id=\"tel\" required=\"\" maxlength=\"13\"/>\n");
      out.write("                  </div>  \n");
      out.write("                   \n");
      out.write("                 <div class=\"form-group\"> \n");
      out.write("                    <label for=\"email\">Email:</label>\n");
      out.write("                    <input class=\"form-control\" type=\"email\" name=\"email\" value=\"\" size=\"30\" id=\"email\" required=\"\" maxlength=\"30\"/>\n");
      out.write("                 </div>   \n");
      out.write("                 \n");
      out.write("                 \n");
      out.write("                 <div class=\"form-group\"> \n");
      out.write("                    <label for=\"password\">Mot de passe:</label>    \n");
      out.write("                    <input type=\"password\" class=\"form-control\" name=\"password\" value=\"\" id=\"password\" required=\"\" maxlength=\"10\"/>\n");
      out.write("                 </div>                                             \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                <label for=\"sexe\">Sexe:</label>\n");
      out.write("                <div class=\"radio\">\n");
      out.write("                <label>\n");
      out.write("                    <input type=\"radio\" name=\"sexe\" value=\"F\" id=\"femme\" checked=\"true\"/>\n");
      out.write("                Femme\n");
      out.write("                </label>\n");
      out.write("\n");
      out.write("                <label>\n");
      out.write("                    <input type=\"radio\" name=\"sexe\" value=\"M\" id=\"homme\"/>\n");
      out.write("                Homme\n");
      out.write("                </label>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                <label >Permis de conduire:</label>\n");
      out.write("                <div class=\"radio\">\n");
      out.write("                <label>\n");
      out.write("                    <input type=\"radio\" name=\"permis\" value=\"OUI\" id=\"permisOui\" checked=\"true\"/>\n");
      out.write("                OUI\n");
      out.write("                </label>\n");
      out.write("\n");
      out.write("                <label>\n");
      out.write("                    <input type=\"radio\" name=\"permis\" value=\"NON\" id=\"permisNon\"/>\n");
      out.write("                NON\n");
      out.write("                </label>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                <label for=\"photo\" >Photo</label>\n");
      out.write("                <input class=\"form-control-file\" type=\"file\" name=\"photo\" value=\"photo\" id=\"photo\"/>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                <button class=\"btn btn-primary btn-md\" type=\"submit\" name=\"envoyer\" value=\"Envoyer\">\n");
      out.write("                Envoyer \n");
      out.write("                </button>\n");
      out.write("                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("                <button class=\"btn btn-warning btn-md\" type=\"reset\" name=\"annuler\" value=\"annuler\">\n");
      out.write("                Annuler\n");
      out.write("                </button>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("        </form>    \n");
      out.write("    \n");
      out.write("\n");
      out.write("</div> \n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includeFooter.jsp", out, false);
      out.write(" \n");
      out.write("\n");
      out.write("          <script> $(function() {\n");
      out.write("\n");
      out.write("            $( \"#datenaissance\" ).datepicker();\n");
      out.write("\n");
      out.write("          });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
